services:
  # Backend API service
  - type: web
    name: thecompletelazytrend-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: FRONTEND_URL
        fromService:
          name: thecompletelazytrend-frontend
          type: static_site
          property: url
      - key: OPENROUTER_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: DASHSCOPE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

  # Frontend static site
  - type: static_site
    name: thecompletelazytrend-frontend
    env: static
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: thecompletelazytrend-backend
          type: web
          property: url
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
