services:
  - type: web
    name: thecompletelazytrend-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://thecompletelazytrend-backend.onrender.com
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: VITE_STRIPE_PRODUCT_ID
        sync: false
      - key: VITE_STRIPE_PRICE_ID
        sync: false
      - key: VITE_STRIPE_CONNECT_ACCOUNT_ID
        sync: false
