services:
  - type: web
    name: thecompletelazytrend-backend
    env: node
    buildCommand: npm ci && npm install stripe@18.0.0
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRODUCT_ID
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_CONNECT_ACCOUNT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: DASHSCOPE_API_KEY
        sync: false
      - key: FEEDBACK_EMAIL
        value: info@lazy-trends.com
      - key: EMAIL_FROM
        value: noreply@lazy-trends.com
